max-line-length: 79
doc-warnings: true
test-warnings: true
member-warnings: true
autodetect: false

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line => conflit with D213
    - D203 # 1 blank line required before class docstring (found 0) => conflit with black
    - D417 # Missing argument descriptions in the docstring (argument(s) shift_to_right are missing descriptions in '__init__' docstring)

pep8:
  full: true

vulture:
  run: true

mypy:
  run: true

bandit:
  run: true
