max-line-length: 79
doc-warnings: true
test-warnings: true
member-warnings: true
autodetect: false

pydocstyle:
  disable:
    - D104 # Missing docstring in public package
    - D202 # No blank lines allowed after function docstring (found 1)
    - D203 # 1 blank line required before class docstring (found 0) => conflit with black
    - D205 # 1 blank line required between summary line and description (found 0)
    - D212 # Multi-line docstring summary should start at the first line => conflit with D213
    - D404 # First word of the docstring should not be `This`
    - D407 # Missing dashed underline after section ('Args', 'Returns', etc.)
    - D413 # Missing blank line after last section ('Args', 'Returns', etc.)
    - D415 # First line should end with a period, question mark, or exclamation point (not 'd')
    - D417 # Missing argument descriptions in the docstring (argument(s) shift_to_right are missing descriptions in '__init__' docstring)

pylint:
  disable:
    - unnecessary-ellipsis
    - unnecessary-pass

pep8:
  full: true

vulture:
  run: true

mypy:
  run: true

bandit:
  run: true
  options:
    config: bandit.yaml
